version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: productDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bhaga@0612
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - capstone-project
    ports:
      - "5436:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bhag1988/product-service:v1.0
    container_name: product-service_container
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/productDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Bhaga@0612
    ports:
      - "8090:8090"
    networks:
      - capstone-project

networks:
  capstone-project:

volumes:
  postgres-data: