spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productDB
    username: postgres
    password: Bhaga@0612
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8090